<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="18621" started-at="2023-01-18T19:02:14 IST" finished-at="2023-01-18T19:02:33 IST">
    <groups>
    </groups>
    <test name="Test" duration-ms="18621" started-at="2023-01-18T19:02:14 IST" finished-at="2023-01-18T19:02:33 IST">
      <class name="com.test.TestCase01">
        <test-method status="PASS" signature="BS()[pri:0, instance:com.test.TestCase01@619713e5]" name="BS" is-config="true" duration-ms="10" started-at="2023-01-18T19:02:14 IST" finished-at="2023-01-18T19:02:14 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BS -->
        <test-method status="PASS" signature="Setup()[pri:0, instance:com.test.TestCase01@619713e5]" name="Setup" is-config="true" duration-ms="12762" started-at="2023-01-18T19:02:14 IST" finished-at="2023-01-18T19:02:27 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method status="FAIL" signature="verifyTestCase01()[pri:0, instance:com.test.TestCase01@619713e5]" name="verifyTestCase01" duration-ms="5113" started-at="2023-01-18T19:02:27 IST" finished-at="2023-01-18T19:02:32 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [[IPHONE, SAMSUNG GALAXY, SONY XPERIA]] but found [[null, SAMSUNG GALAXY, SONY XPERIA]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [[IPHONE, SAMSUNG GALAXY, SONY XPERIA]] but found [[null, SAMSUNG GALAXY, SONY XPERIA]]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.april.Utility.Libraryclass.custom_Verifyorder(Libraryclass.java:76)
at com.test.TestCase01.verifyTestCase01(TestCase01.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTestCase01 -->
        <test-method status="PASS" signature="closebrower()[pri:0, instance:com.test.TestCase01@619713e5]" name="closebrower" is-config="true" duration-ms="383" started-at="2023-01-18T19:02:33 IST" finished-at="2023-01-18T19:02:33 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closebrower -->
      </class> <!-- com.test.TestCase01 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
